#!/usr/bin/env node
/**
 * Reads data/light_rail_routes_and_stops.csv and writes utils/lr-data.ts.
 * Run: yarn build:lr-data
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const csvPath = path.join(root, 'data/light_rail_routes_and_stops.csv')
const outPath = path.join(root, 'utils/lr-data.ts')

function parseCsv(text) {
  const lines = text.replace(/^\uFEFF/, '').trimEnd().split(/\r?\n/)
  const header = lines[0].split(',')
  const idx = Object.fromEntries(header.map((h, i) => [h.trim(), i]))
  const required = [
    'Line Code',
    'Direction',
    'Stop Code',
    'Stop ID',
    'Chinese Name',
    'English Name',
    'Sequence',
  ]
  for (const col of required) {
    if (idx[col] == null) throw new Error(`Missing CSV column: ${col}`)
  }
  return lines.slice(1).filter(Boolean).map((line) => {
    const cols = line.split(',')
    return {
      route: cols[idx['Line Code']].trim(),
      dir: Number(cols[idx['Direction']].trim()),
      stopCode: cols[idx['Stop Code']].trim(),
      stopId: cols[idx['Stop ID']].trim(),
      tc: cols[idx['Chinese Name']].trim(),
      en: cols[idx['English Name']].trim(),
      seq: Number(cols[idx['Sequence']].trim()),
    }
  })
}

function esc(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

const rows = parseCsv(fs.readFileSync(csvPath, 'utf8'))

/** @type {Map<string, { id: string, code: string, en: string, tc: string }>} */
const stations = new Map()
/** @type {Map<string, Map<number, { seq: number, id: string }[]>>} */
const routeDirs = new Map()

for (const row of rows) {
  if (!stations.has(row.stopId)) {
    stations.set(row.stopId, {
      id: row.stopId,
      code: row.stopCode,
      en: row.en,
      tc: row.tc,
    })
  }
  if (!routeDirs.has(row.route)) routeDirs.set(row.route, new Map())
  const dirs = routeDirs.get(row.route)
  if (!dirs.has(row.dir)) dirs.set(row.dir, [])
  dirs.get(row.dir).push({ seq: row.seq, id: row.stopId })
}

function dedupeConsecutive(ids) {
  const out = []
  for (const id of ids) {
    if (out[out.length - 1] !== id) out.push(id)
  }
  return out
}

const stationList = [...stations.values()].sort(
  (a, b) => Number(a.id) - Number(b.id)
)

const routes = [...routeDirs.keys()].sort((a, b) =>
  a.localeCompare(b, 'en', { numeric: true })
)

const stationBlocks = stationList
  .map(
    (s) =>
      `  { id: '${esc(s.id)}', code: '${esc(s.code)}', label: { en: '${esc(s.en)}', tc: '${esc(s.tc)}' } },`
  )
  .join('\n')

const routeBlocks = routes
  .map((code) => {
    const dirs = routeDirs.get(code)
    const dirBlocks = [...dirs.keys()]
      .sort((a, b) => a - b)
      .map((dir) => {
        const ordered = dirs
          .get(dir)
          .sort((a, b) => a.seq - b.seq)
          .map((x) => x.id)
        const ids = dedupeConsecutive(ordered)
        return `      { dir: ${dir}, stopIds: [${ids.map((id) => `'${esc(id)}'`).join(', ')}] },`
      })
      .join('\n')
    return `  {\n    code: '${esc(code)}',\n    directions: [\n${dirBlocks}\n    ],\n  },`
  })
  .join('\n')

const file = `/** Generated by scripts/build-lr-data.mjs — do not edit by hand. */
/** Source: data/light_rail_routes_and_stops.csv */

export type LrStation = {
  id: string
  code: string
  label: { en: string; tc: string }
}

export type LrRouteDirection = {
  dir: 1 | 2
  stopIds: readonly string[]
}

export type LrRoute = {
  code: string
  directions: readonly LrRouteDirection[]
}

export const LR_STATIONS: readonly LrStation[] = [
${stationBlocks}
] as const

export const LR_ROUTES: readonly LrRoute[] = [
${routeBlocks}
] as const

const KNOWN_LR_STATION = new Set(LR_STATIONS.map((s) => s.id))
const KNOWN_LR_ROUTE = new Set(LR_ROUTES.map((r) => r.code))
const STATION_BY_ID = new Map(LR_STATIONS.map((s) => [s.id, s]))
const ROUTE_BY_CODE = new Map(LR_ROUTES.map((r) => [r.code, r]))

export function isKnownLrStation(stationId: string): boolean {
  return KNOWN_LR_STATION.has(stationId)
}

export function isKnownLrRoute(routeCode: string): boolean {
  return KNOWN_LR_ROUTE.has(routeCode)
}

export function getLrStation(stationId: string): LrStation | undefined {
  return STATION_BY_ID.get(stationId)
}

export function getLrRoute(routeCode: string): LrRoute | undefined {
  return ROUTE_BY_CODE.get(routeCode)
}

export function getLrRouteStopIds(
  routeCode: string,
  dir: 1 | 2
): readonly string[] {
  const route = getLrRoute(routeCode)
  const direction = route?.directions.find((d) => d.dir === dir)
  return direction?.stopIds ?? []
}
`

fs.writeFileSync(outPath, file)
console.error(
  `build-lr-data: ${stationList.length} stations, ${routes.length} routes → ${path.relative(root, outPath)}`
)
